### PR TITLE
fix: non-op logger in itests

### PR DESCRIPTION
**Pull request by bap2pecs**
## Summary

https://github.com/babylonchain/finality-provider/issues/449

also per @maurolacy's suggestion https://github.com/babylonchain/finality-provider/pull/447#discussion_r1660667470, I moved the logger changes to this PR

also added some other log related improvements in this PR

## Test Plan

```
make lint
```

wait for CI

### CODE REVIEW

**Comment by bap2pecs** [comment]
weird that CI failed due to

```
=== RUN   TestFastSync
    babylon_node_handler.go:148: babylon log file: /tmp/zBabylonTest698224887/babylon.log
service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
    eotsmanager_handler.go:23: 
                Error Trace:    /home/circleci/project/itest/eotsmanager_handler.go:23
                                                        /home/circleci/project/itest/babylon/babylon_test_manager.go:72
                                                        /home/circleci/project/itest/babylon/babylon_test_manager.go:117
                                                        /home/circleci/project/itest/babylon/babylon_e2e_test.go:148
                Error:          Received unexpected error:
                                intercept already started
                Test:           TestFastSync
--- FAIL: TestFastSync (0.33s)
```

not sure why this PR can be related

**Comment by bap2pecs** [comment]
hmm CI failed again but this time due to a different flaky test issue: https://github.com/babylonchain/finality-provider/issues/439

**Comment by bap2pecs** [comment]
ok now the CI passed. has been very flaky today lol

**Comment by SebastianElvis** [comment]
Maybe this PR can go to the `dev` branch rather than the base branch?

**Comment by bap2pecs** [comment]
> Maybe this PR can go to the `dev` branch rather than the base branch?

there isn't op related code in dev so this PR cannot be on `dev`. but we can create a separate PR to fix similar places in `dev`

**Review by SebastianElvis — APPROVED** [review]

**Comment by bap2pecs** [comment]
added https://github.com/babylonchain/finality-provider/pull/456

**Pull request merged**
