### PR TITLE
chore: merge latest changes from dev to consumer chain support branch

### PR DESCRIPTION
**Pull request by gusin13**
Closes https://github.com/babylonchain/finality-provider/issues/334.

### CODE REVIEW

**Comment by maurolacy** [comment]
Nit: Let's use Closes instead of Fixes in the description, so that merging auto-closes the issue.

**Review by maurolacy — APPROVED** [review]
Looks good. Approving with 👀 closed.

**Comment by bap2pecs** [comment]
@SebastianElvis @maurolacy what's the latest update on this branch? should we consolidate w the branch https://github.com/babylonchain/finality-provider/tree/base/eth-support?

**Comment by maurolacy** [comment]
Closing in favour of #338, for a cleaner commit history.

**Comment by maurolacy** [comment]
Re-opening as #338 is marked as conflicted with base.

**Comment by gusin13** [comment]
please refer to https://github.com/babylonchain/finality-provider/pull/339

**Pull request closed without merging**
