### PR TITLE
chore: CI parallelism and caching

### PR DESCRIPTION
**Pull request by bap2pecs**
## Summary

those e2e tests are complicated and takes very long to run b/c they require setting up multiple systems e.g. Babylon node, multiple EOTS managers, multiple FPs, L1 and L2 chains

I used a few strategies to make it run faster:
- [x] put each our op e2e tests in a separate container using CircleCI's built-in parallelism feature
- [x] use caching to avoid re-building `babylond` from scratch every time
- [x] use caching to avoid build the tests from scratch every time

references:
- https://circleci.com/docs/parallelism-faster-jobs/
- https://circleci.com/docs/test-splitting-tutorial/#step-two-set-up-test-splitting
- https://circleci.com/docs/caching/#using-keys-and-templates
- https://circleci.com/docs/caching-strategy/#cache-optimization
- https://circleci.com/developer/orbs/orb/circleci/go
- https://circleci.com/docs/env-vars/#built-in-environment-variables

## Test Plan
CI passed.

this gets our op e2e tests run time down from 15 minutes to 6 minutes

<details><summary>before:</summary>
image
</details>

<details><summary>after:</summary>
image
</details>

this also gets the Babylon e2e tests down from 12 minutes to 3 minutes

<details><summary>before:</summary>
image
</details>

<details><summary>after:</summary>
image
</details>

### CODE REVIEW

**Comment by bap2pecs** [comment]
not sure why this doesn't work. @SebastianElvis has anyone in the team used `circleci tests run` before?

```
go: downloading github.com/hashicorp/go-getter v1.7.3
go: downloading github.com/klauspost/compress v1.17.7
go: downloading github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
circleci tests run --command "xargs gotestsum --junitfile junit.xml --format testname -- -mod=readonly -timeout=25m -v github.com/babylonchain/finality-provider/itest/opstackl2 -count=1 --tags=e2e_op" --split-by=timings --timings-type=name
Installing circleci-tests-plugin-cli plugin.
circleci-tests-plugin-cli plugin Installed. Version: 1.0.7332-dfcf8a1
WARN[2024-07-09T23:32:55Z] No test names found in input source. If you were expecting test names, please check your input source. 
There was an error reading historical timing data: file does not existRequested weighting by historical based timing, but they are not present. Falling back to weighting by name.
```

I also posted the q on https://discuss.circleci.com/t/how-to-split-tests-in-the-same-go-file-using-filter-such-as-run-testfoo/51440 but didn't get any response

**Comment by bap2pecs** [comment]
great work! this is much needed

Jake Gyllenhaal Sneaker Shopping - 5quxvnjc77jutz5KGR

**Review by SebastianElvis — APPROVED** [review]
Great work on cutting CI runtime by >2x :clap:

**Comment by bap2pecs** [comment]
bcd tests failed a few times w:

image

so I am adding the same fix I did in our tests here: https://github.com/babylonchain/finality-provider/pull/503/commits/ced8564e6b49ba91b4189144592d34631bd364c2

**Comment by bap2pecs** [comment]
ok all CI passed now

**Pull request merged**
